/* Q01: known-answer tests for the shared PNG decoder (tests/png.cjs).
 *
 * Every expectation here is hand-computed from the PNG specification, not
 * produced by either decoder implementation, so the file is an independent
 * trusted reference for the runners that compare screenshot pixels.
 */
const test = require("node:test");
const assert = require("node:assert/strict");
const { pngDecode, pngEncode, pngEncodeRows } = require("./png.cjs");

/* ---- the pass-3 known-answer that exposed the Paeth bug ----------------
 * A 2x2 RGB image, grayscale values [20,40; 0,20], first row filter 0,
 * second row filter 4 (Paeth) with raw bytes 236,236,236,0,0,0.
 *
 * Row 2, pixel 1: a=0 b=20 c=0 -> p=20 -> pa=20 pb=0 pc=20 -> b=20 ->
 *   236+20 = 256 mod 256 = 0.  (The buggy formula also picked b here.)
 * Row 2, pixel 2: a=0 b=40 c=20 -> p=20 -> pa=20 pb=20 pc=0 -> c=20 ->
 *   0+20 = 20.  (The buggy pc=|a+c-2b|=60 loses this tie to a and decodes
 *   0 instead of 20 - exactly the untrustworthy statistics of pass 3.)
 */
/* The exact stored bytes the plan prescribes, asserted independently of
 * both the encoder and the decoder by inflating the IDAT directly. */
const KA_RAW = [0, 20, 20, 20, 40, 40, 40, 4, 236, 236, 236, 0, 0, 0];
const KNOWN_ANSWER = pngEncodeRows(2, 2, 2, [
  { filter: 0, bytes: [20, 20, 20, 40, 40, 40] },
  { filter: 4, bytes: [0, 0, 0, 20, 20, 20] },
]);

test("Q01: the pass-3 Paeth known-answer decodes to its hand-computed pixels", () => {
  /* the encoded file really carries the plan's raw scanline bytes */
  const zlib = require("node:zlib");
  const at = KNOWN_ANSWER.indexOf(Buffer.from([73, 68, 65, 84]));
  const len = KNOWN_ANSWER.readUInt32BE(at - 4);
  const raw = zlib.inflateSync(KNOWN_ANSWER.subarray(at + 4, at + 4 + len));
  assert.deepEqual([...raw], KA_RAW, "the known-answer bytes are exact");
  const img = pngDecode(KNOWN_ANSWER);
  assert.equal(img.w, 2);
  assert.equal(img.h, 2);
  /* RGBA: [20,40] on the first row, [0,20] on the second */
  assert.deepEqual(
    [...img.px],
    [
      20, 20, 20, 255, 40, 40, 40, 255,
      0, 0, 0, 255, 20, 20, 20, 255,
    ],
  );
});

/* A 3x3 RGB image whose rows use every filter type, so each row decodes
 * through a different predictor. Row bytes are generated by the forward
 * transform in pngEncodeRows from the exact target pixels below. */
const TARGET = [
  [12, 34, 56], [78, 90, 13], [57, 79, 91],
  [11, 200, 30], [140, 5, 250], [99, 100, 101],
  [0, 255, 128], [64, 32, 16], [250, 128, 64],
];
const rgbBytes = (rows) => rows.flat(); /* rows are [r,g,b] pixel entries */
const FILTERS = [0, 1, 2, 3, 4, 0, 4, 2, 1];

test("Q01: all five filters decode the same pixels (RGB)", () => {
  const png = pngEncodeRows(3, 3, 2, FILTERS.map((f, y) => ({ filter: f, bytes: rgbBytes(TARGET.slice(y * 3, y * 3 + 3)) })));
  const img = pngDecode(png);
  assert.deepEqual(
    [...img.px],
    TARGET.flatMap((p) => [...p, 255]),
  );
});

test("Q01: all five filters decode the same pixels (RGBA)", () => {
  const rgba = (r, g, b, a) => [r, g, b, a];
  const grid = [
    rgba(10, 20, 30, 255), rgba(200, 100, 50, 128), rgba(0, 0, 0, 0),
    rgba(255, 255, 255, 1), rgba(17, 34, 51, 77), rgba(88, 44, 22, 250),
    rgba(5, 5, 5, 5), rgba(120, 60, 240, 200), rgba(1, 2, 3, 4),
  ];
  const rows = [0, 4, 1, 2, 3, 4, 0, 1, 2].map((f, y) => ({
    filter: f,
    bytes: grid.slice(y * 3, y * 3 + 3).flat(),
  }));
  const img = pngDecode(pngEncodeRows(3, 3, 6, rows));
  assert.deepEqual([...img.px], grid.flat());
});

test("Q01: Paeth tie cases pick the left pixel per the spec", () => {
  /* pa = pb = pc = 0 (all predictors equal) must decode to a (left).
   * Row 2 filter 4 with raw 0,0,0,0: predictors a=b=c=50 -> decode 50. */
  const rows = [
    { filter: 0, bytes: [50, 50, 50] },
    { filter: 4, bytes: [50, 50, 50] },
  ];
  const img = pngDecode(pngEncodeRows(1, 2, 2, rows));
  assert.deepEqual([...img.px], [50, 50, 50, 255, 50, 50, 50, 255]);
});

test("Q01: identical pixels encoded with different filters decode identically", () => {
  const one = pngEncodeRows(2, 2, 2, [
    { filter: 0, bytes: rgbBytes([[1, 2, 3], [4, 5, 6]]) },
    { filter: 0, bytes: rgbBytes([[7, 8, 9], [10, 11, 12]]) },
  ]);
  const two = pngEncodeRows(2, 2, 2, [
    { filter: 1, bytes: rgbBytes([[1, 2, 3], [4, 5, 6]]) },
    { filter: 4, bytes: rgbBytes([[7, 8, 9], [10, 11, 12]]) },
  ]);
  assert.deepEqual(
    [...pngDecode(one).px],
    [...pngDecode(two).px],
    "filter choice must not change decoded pixels",
  );
});

test("Q01: the runner encoder round-trips through the shared decoder", () => {
  const px = new Uint8Array(4 * 2 * 4);
  for (let i = 0; i < px.length; i++) px[i] = (i * 37) & 255;
  const img = pngDecode(pngEncode(4, 2, px));
  assert.equal(img.w, 4);
  assert.equal(img.h, 2);
  assert.deepEqual([...img.px], [...px]);
});

/* Malformed and unsupported inputs must fail loudly, never decode wrongly. */
const withIHDR = (depth, colorType, interlace = 0) => {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(2, 0);
  ihdr.writeUInt32BE(1, 4);
  ihdr[8] = depth;
  ihdr[9] = colorType;
  ihdr[12] = interlace;
  return Buffer.concat([
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
    Buffer.concat([
      Buffer.from([0, 0, 0, 13, 73, 72, 68, 82]),
      ihdr,
      Buffer.from([0, 0, 0, 0, 0, 0, 0, 0]),
    ]),
    Buffer.from([0, 0, 0, 0, 73, 69, 78, 68]),
  ]);
};

test("Q01: malformed and unsupported PNGs fail loudly", () => {
  assert.throws(() => pngDecode(Buffer.from([1, 2, 3])), /not a PNG/);
  assert.throws(() => pngDecode(withIHDR(16, 6)), /bit depth/);
  assert.throws(() => pngDecode(withIHDR(8, 3)), /color type/);
  assert.throws(() => pngDecode(withIHDR(8, 6, 1)), /interlace/);
  assert.throws(() => pngDecode(withIHDR(8, 6)), /no image data/);
  /* a scanline whose filter byte is 5 */
  const bad = Buffer.concat([
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
    Buffer.from([
      0, 0, 0, 13, 73, 72, 68, 82,
      0, 0, 0, 2, 0, 0, 0, 1, 8, 2, 0, 0, 0,
    ]),
    Buffer.from([
      0, 0, 0, 8, 73, 68, 65, 84,
      120, 156, 5, 192, 193, 1, 0, 0,
    ]),
    Buffer.from([0, 0, 0, 0, 73, 69, 78, 68]),
  ]);
  assert.throws(() => pngDecode(bad), /filter|inflate|truncated|data/i);
});

test("Q01: a truncated scanline buffer is rejected", () => {
  const good = pngEncodeRows(2, 2, 2, [
    { filter: 0, bytes: [1, 2, 3, 4, 5, 6] },
    { filter: 0, bytes: [7, 8, 9, 10, 11, 12] },
  ]);
  /* drop the last 4 bytes of the IDAT payload: rewrap the chunk */
  const idatStart = good.indexOf(Buffer.from([73, 68, 65, 84]));
  const idatLen = good.readUInt32BE(idatStart - 4);
  const idat = good.subarray(idatStart + 4, idatStart + 4 + idatLen - 4);
  const rebuilt = Buffer.concat([
    good.subarray(0, idatStart - 4),
    Buffer.from([0, 0, 0, idat.length, 73, 68, 65, 84]),
    idat,
    Buffer.from([0, 0, 0, 0, 0, 0, 0, 0]),
    Buffer.from([0, 0, 0, 0, 73, 69, 78, 68]),
  ]);
  assert.throws(() => pngDecode(rebuilt), /truncated|inflate/);
});

/* Structural cross-check of a real saved artifact: the baselines the
 * runners compare are 1440x813 screenshots, so the decoder must agree. */
test("Q01: a saved baseline decodes at its recorded size", () => {
  const fs = require("node:fs");
  const path = require("node:path");
  const dir = path.join(__dirname, "..", "shots", "repair-pass3");
  const file = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".png"))
    .map((f) => path.join(dir, f))
    .find((p) => fs.statSync(p).size > 10000);
  assert.ok(file, "a pass-3 baseline exists");
  const img = pngDecode(fs.readFileSync(file));
  assert.equal(img.w, 1440);
  assert.equal(img.h, 813);
  assert.equal(img.px.length, 1440 * 813 * 4);
});
